[variables]
PHP_VERSION = "8.2"

[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.mbstring",
  "php82Extensions.pdo_mysql",
  "php82Extensions.gd",
  "php82Extensions.posix",
  "php82Extensions.pcntl",
  "php82Extensions.bcmath",
  "nodejs",
  "npm"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run build"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
